services:
  central:
    build:
      context: .
      dockerfile: deploy/docker/central.Dockerfile
    ports:
      - "8000:8000"
  collector:
    build:
      context: .
      dockerfile: deploy/docker/collector.Dockerfile
    depends_on:
      - central
